
(* X_CORE_INFO = "mig_v3_92_ddr2_ddr2_s6, Coregen 14.7" , CORE_GENERATION_INFO = "ddr2_ddr2_s6,mig_v3_92,{component_name=ddr2_mcb, C3_MEM_INTERFACE_TYPE=DDR2_SDRAM, C3_CLK_PERIOD=3000, C3_MEMORY_PART=ede1116axxx-8e, C3_MEMORY_DEVICE_WIDTH=16, C3_OUTPUT_DRV=FULL, C3_RTT_NOM=50OHMS, C3_DQS#_ENABLE=YES, C3_HIGH_TEMP_SR=NORMAL, C3_PORT_CONFIG=Two 32-bit bi-directional and four 32-bit unidirectional ports, C3_MEM_ADDR_ORDER=ROW_BANK_COLUMN, C3_PORT_ENABLE=Port0, C3_CLASS_ADDR=II, C3_CLASS_DATA=II, C3_INPUT_PIN_TERMINATION=CALIB_TERM, C3_DATA_TERMINATION=25 Ohms, C3_CLKFBOUT_MULT_F=2, C3_CLKOUT_DIVIDE=1, C3_DEBUG_PORT=0, INPUT_CLK_TYPE=Differential, LANGUAGE=Verilog, SYNTHESIS_TOOL=Foundation_ISE, NO_OF_CONTROLLERS=1}" *)
module ddr2_mcb #
(

   inout  [C3_NUM_DQ_PINS-1:0]                      mcb3_dram_dq,
   output [C3_MEM_ADDR_WIDTH-1:0]                   mcb3_dram_a,
   output [C3_MEM_BANKADDR_WIDTH-1:0]               mcb3_dram_ba,
   output                                           mcb3_dram_ras_n,
   output                                           mcb3_dram_cas_n,
   output                                           mcb3_dram_we_n,
   output                                           mcb3_dram_odt,
   output                                           mcb3_dram_cke,
   output                                           mcb3_dram_dm,
   inout                                            mcb3_dram_udqs,
   inout                                            mcb3_dram_udqs_n,
   inout                                            mcb3_rzq,
   inout                                            mcb3_zio,
   output                                           mcb3_dram_udm,
   input                                            c3_sys_clk_p,
   input                                            c3_sys_clk_n,
   input                                            c3_sys_rst_i,
   output                                           c3_calib_done,
   output                                           c3_clk0,
   output                                           c3_rst0,
   inout                                            mcb3_dram_dqs,
   inout                                            mcb3_dram_dqs_n,
   output                                           mcb3_dram_ck,
   output                                           mcb3_dram_ck_n,
      input		c3_s0_axi_aclk   ,
      input		c3_s0_axi_aresetn,
      input [C3_S0_AXI_ID_WIDTH - 1:0]	c3_s0_axi_awid   ,
      input [C3_S0_AXI_ADDR_WIDTH - 1:0]	c3_s0_axi_awaddr ,
      input [7:0]	c3_s0_axi_awlen  ,
      input [2:0]	c3_s0_axi_awsize ,
      input [1:0]	c3_s0_axi_awburst,
      input [0:0]	c3_s0_axi_awlock ,
      input [3:0]	c3_s0_axi_awcache,
      input [2:0]	c3_s0_axi_awprot ,
      input [3:0]	c3_s0_axi_awqos  ,
      input		c3_s0_axi_awvalid,
      output		c3_s0_axi_awready,
      input [C3_S0_AXI_DATA_WIDTH - 1:0]	c3_s0_axi_wdata  ,
      input [C3_S0_AXI_DATA_WIDTH/8 - 1:0]	c3_s0_axi_wstrb  ,
      input		c3_s0_axi_wlast  ,
      input		c3_s0_axi_wvalid ,
      output		c3_s0_axi_wready ,
      output [C3_S0_AXI_ID_WIDTH - 1:0]	c3_s0_axi_bid    ,
      output [C3_S0_AXI_ID_WIDTH - 1:0]	c3_s0_axi_wid    ,
      output [1:0]	c3_s0_axi_bresp  ,
      output		c3_s0_axi_bvalid ,
      input		c3_s0_axi_bready ,
      input [C3_S0_AXI_ID_WIDTH - 1:0]	c3_s0_axi_arid   ,
      input [C3_S0_AXI_ADDR_WIDTH - 1:0]	c3_s0_axi_araddr ,
      input [7:0]	c3_s0_axi_arlen  ,
      input [2:0]	c3_s0_axi_arsize ,
      input [1:0]	c3_s0_axi_arburst,
      input [0:0]	c3_s0_axi_arlock ,
      input [3:0]	c3_s0_axi_arcache,
      input [2:0]	c3_s0_axi_arprot ,
      input [3:0]	c3_s0_axi_arqos  ,
      input		c3_s0_axi_arvalid,
      output		c3_s0_axi_arready,
      output [C3_S0_AXI_ID_WIDTH - 1:0]	c3_s0_axi_rid    ,
      output [C3_S0_AXI_DATA_WIDTH - 1:0]	c3_s0_axi_rdata  ,
      output [1:0]	c3_s0_axi_rresp  ,
      output		c3_s0_axi_rlast  ,
      output		c3_s0_axi_rvalid ,
      input		c3_s0_axi_rready 
);
endmodule